name: Build and Push (Frontend & Backend)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ env.BACKEND_IMAGE }}:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # === Frontend ===
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/dist/browser

      # === Backend ===
      - name: Setup QEMU & Buildx (Docker)
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest
