name: Build & Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Nombre del bucket S3 donde desplegar el frontend'
        required: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to S3 (sin ACLs)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ github.event.inputs.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: frontend/dist/mi-app/browser/

      - name: Crear distribución CloudFront con HTTPS
        id: cloudfront
        run: |
          DIST_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Comment=='proyecto-base-frontend'].Id" --output text)
          if [ -z "$DIST_ID" ]; then
            echo "Creando nueva distribución CloudFront..."
            DIST_ID=$(aws cloudfront create-distribution \
              --origin-domain-name "${{ github.event.inputs.bucket }}.s3.amazonaws.com" \
              --default-root-object index.html \
              --comment "proyecto-base-frontend" \
              --query "Distribution.Id" --output text)
          fi
          echo "DIST_ID=$DIST_ID" >> $GITHUB_ENV

      - name: Mostrar URL pública HTTPS
        run: |
          DOMAIN=$(aws cloudfront get-distribution --id ${{ env.DIST_ID }} \
            --query "Distribution.DomainName" --output text)
          echo "Frontend desplegado y accesible por HTTPS en: https://$DOMAIN"
