name: Build and Push (Frontend & Backend)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      backend-image: ${{ env.BACKEND_IMAGE }}:latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # 4️⃣ Debug: mostrar contenido del build
      - name: Debug frontend build folder
        run: |
          echo "Ruta real del build: frontend/dist/mi-app"
          ls -R frontend/dist/mi-app

      # 5️⃣ Subir artefacto del frontend
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/mi-app

      # 6️⃣ Setup QEMU & Buildx (Docker backend)
      - name: Setup QEMU & Buildx
        uses: docker/setup-buildx-action@v2

      # 7️⃣ Login GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 8️⃣ Build & push backend
      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest
