name: Build & Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Nombre del bucket S3 donde desplegar el frontend'
        required: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to S3 (sin ACLs)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ github.event.inputs.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: frontend/dist/mi-app/browser/

      # 6️⃣ Configurar credenciales AWS para CloudFront
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Crear distribución CloudFront con HTTPS
        id: cloudfront
        run: |
          # Definir archivo JSON de distribución mínimo
          cat > dist-config.json <<EOF
          {
            "CallerReference": "$(date +%s)",
            "Comment": "proyecto-base-frontend",
            "DefaultCacheBehavior": {
              "TargetOriginId": "S3-${{ github.event.inputs.bucket }}",
              "ViewerProtocolPolicy": "redirect-to-https",
              "TrustedSigners": {
                "Enabled": false,
                "Quantity": 0
              },
              "ForwardedValues": {
                "QueryString": false,
                "Cookies": { "Forward": "none" }
              },
              "MinTTL": 0
            },
            "Origins": {
              "Quantity": 1,
              "Items": [
                {
                  "Id": "S3-${{ github.event.inputs.bucket }}",
                  "DomainName": "${{ github.event.inputs.bucket }}.s3.amazonaws.com",
                  "S3OriginConfig": { "OriginAccessIdentity": "" }
                }
              ]
            },
            "Enabled": true,
            "DefaultRootObject": "index.html"
          }
          EOF

          # Crear distribución
          DIST_ID=$(aws cloudfront create-distribution \
            --distribution-config file://dist-config.json \
            --query "Distribution.Id" --output text)
          echo "DIST_ID=$DIST_ID" >> $GITHUB_ENV


      - name: Mostrar URL pública HTTPS
        run: |
          DOMAIN=$(aws cloudfront get-distribution --id ${{ env.DIST_ID }} \
            --query "Distribution.DomainName" --output text)
          echo "Frontend desplegado y accesible por HTTPS en: https://$DOMAIN"
