name: Build and Push Frontend & Backend (Debug Build)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}/backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Debug: imprimir directorio inicial
      - name: Debug root directory
        run: |
          echo "Directorio actual: $(pwd)"
          ls -l
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      # 4️⃣ Instalar dependencias del frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      # 5️⃣ Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # 6️⃣ Debug: mostrar contenido del build
      - name: Debug frontend build folder
        run: |
          echo "Ruta probable del build: frontend/build"
          ls -R frontend/build || echo "No se encontró frontend/build"
          echo "También revisando frontend/dist/browser por si acaso"
          ls -R frontend/dist/browser || echo "No se encontró frontend/dist/browser"

      # 7️⃣ Subir artefacto
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/build
            frontend/dist/browser  # se sube ambas rutas si existen

      # 8️⃣ Setup QEMU & Buildx (Docker backend)
      - name: Setup QEMU & Buildx
        uses: docker/setup-buildx-action@v2

      # 9️⃣ Login GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 🔟 Build & push backend
      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest
