name: Build & Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: 'Nombre del bucket S3 donde desplegar el frontend'
        required: true

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # 4️⃣ Debug: mostrar contenido del build
      - name: Debug frontend build folder
        run: |
          echo "Ruta real del build: frontend/dist/mi-app"
          ls -R frontend/dist/mi-app

      # 5️⃣ Deploy a S3 (sin ACL)
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ github.event.inputs.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1           # Cambia si tu bucket está en otra región
          SOURCE_DIR: frontend/dist/mi-app/browser/

      # 6️⃣ Confirmación
      - name: Confirmación
        run: |
          echo "Frontend desplegado en: https://${{ github.event.inputs.bucket }}.s3.amazonaws.com"
