name: Crear Frontend Bucket

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-frontend-bucket:
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.set-outputs.outputs.bucket }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Crear bucket S3
        id: set-outputs
        run: |
          BUCKET="proyecto-base-frontend"
          if ! aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
            aws s3api create-bucket --bucket "$BUCKET" --region us-east-1
            aws s3api put-bucket-versioning --bucket "$BUCKET" --versioning-configuration Status=Enabled
            # Bloquear ACLs para compatibilidad con ObjectOwnership
            aws s3api put-public-access-block --bucket "$BUCKET" \
              --public-access-block-configuration BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false
          fi
          echo "bucket=$BUCKET" >> "$GITHUB_OUTPUT"

      - name: Mostrar bucket
        run: |
          echo "Bucket frontend -> ${{ steps.set-outputs.outputs.bucket }}"
