name: CI/CD - Deploy Frontend (prod)

on:
  workflow_run:
    workflows: ["Build & Push Backend"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

env:
  FRONTEND_DIR: frontend
  STATIC_BUILD_DIR: dist/mi-app/browser

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd $FRONTEND_DIR
          npm ci

      - name: Build frontend
        run: |
          cd $FRONTEND_DIR
          npm run build

      - name: Copy static files to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          STATIC_DIR="/var/lib/docker/volumes/static_volume/_data"

          # Crear archivo temporal con la clave SSH
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem

          echo ">>> Preparando carpeta de estáticos en EC2"
          ssh -o StrictHostKeyChecking=no -i key.pem "$EC2_USER@$EC2_HOST" \
            "sudo mkdir -p $STATIC_DIR && sudo chown -R $EC2_USER:$EC2_USER $STATIC_DIR"

          echo ">>> Copiando nuevos estáticos"
          scp -o StrictHostKeyChecking=no -i key.pem -r $FRONTEND_DIR/$STATIC_BUILD_DIR/* "$EC2_USER@$EC2_HOST:$STATIC_DIR"

          # Borrar archivo temporal de la clave
          rm key.pem

      - name: Done
        run: echo ">>> Deploy de frontend finalizado."
